## The native algorithms and entrypoint bodies have one maintained source in
## NicoStan/inst/include/NicoStan/runtime. Rcpp must see exported definitions
## in a .cpp file, so this build step materialises the package translation units.
## Do not edit the generated src/main.cpp or src/burnin_prep_fns.cpp.
##
fn_generate_native_sources <-  function( package_dir,
                                         core_include_dir = NULL) {

        package_dir <-  normalizePath(package_dir, mustWork = TRUE)
        package_name <-  read.dcf(file.path(package_dir, "DESCRIPTION"), fields = "Package")[[1]]
        if (is.null(core_include_dir)) {
                core_include_dir <-  if (package_name == "NicoStan") {
                    file.path(package_dir, "inst", "include", "NicoStan", "runtime")
                } else {
                    system.file("include", "NicoStan", "runtime", package = "NicoStan")
                }
        }
        if (!dir.exists(core_include_dir)) stop("Install the complete NicoStan package before building BayesMVP.")
        ##
        sources <-  c("main.cpp" = "native_api.cpp.in", "burnin_prep_fns.cpp" = "burnin_prep.cpp.in")
        for (target in names(sources)) {
                maintained_path <-  file.path(core_include_dir, sources[[target]])
                if (!file.exists(maintained_path)) stop("Missing maintained native source: ", maintained_path)
                generated_lines <-  c("// GENERATED from NicoStan's canonical native source. Do not edit this file.",
                                       "// Regenerate with inst/native_tools/generate_sources.R, invoked by configure.",
                                       if (package_name == "BayesMVP") "#define NICOSTAN_WITH_BUILTINS 1" else character(),
                                       readLines(maintained_path, warn = FALSE))
                writeLines(generated_lines, file.path(package_dir, "src", target))
        }
        invisible(package_dir)

}
