// Generated by paper_3_general_sampler/build_avx_models.py from Frailty_surv_shared_frailty_Cox.stan.
functions {
  real bmvp_simd_lanes();
  vector fast_exp(vector x);
}


// Cox partial likelihood with lognormal shared frailty. Ties use the Breslow form.

data {
    int<lower=0> N;                    // number of observations
    int<lower=0> K;                    // number of covariates
    int<lower=0> J;                    // number of groups/clusters
    matrix[N, K] X;                    // covariate matrix
    vector[N] t;                       // survival times
    array[N] int<lower=0,upper=1> event;     // event indicator
    array[N] int<lower=1,upper=J> group;     // group assignment
    array[N] int<lower=0> at_risk_count;     // number at risk at each event time
}


parameters {
    vector[J] log_frailty_raw;         // raw log frailties (nuisance parameters)
    vector[K] beta;                    // regression coefficients
    real<lower=0> sigma_frailty;       // frailty standard deviation
}


transformed parameters {
    vector[J] log_frailty;
    vector[N] frailty;
    
    // non-centered parameterization for frailties
    log_frailty = sigma_frailty * log_frailty_raw;
    
    // assign frailties to observations
    for (n in 1:N) {
      frailty[n] = log_frailty[group[n]];
    }
}


model {
    // priors
    beta ~ normal(0, 2);
    log_frailty_raw ~ normal(0, 1);
    sigma_frailty ~ exponential(1);
    
    // Same risk sets and Breslow treatment of tied event times.
    {
      vector[N] eta = X * beta + frailty;
      for (n in 1:N) {
        if (event[n] == 1) {
          vector[N] risk_eta;
          real centre;
          for (j in 1:N) risk_eta[j] = t[j] >= t[n] ? eta[j] : negative_infinity();
          centre = max(risk_eta);
          target += eta[n] - centre - log(sum(fast_exp(risk_eta - centre)));
        }
      }
    }

}


generated quantities {
    real simd_lanes = bmvp_simd_lanes();
    vector[N] log_lik;
    vector[J] frailty_exp = exp(log_frailty);
    
    for (n in 1:N) {
      if (event[n] == 1) {
        real numerator = X[n] * beta + frailty[n];
        real log_sum_exp_denom = negative_infinity();
        for (j in 1:N) {
          if (t[j] >= t[n]) {
            log_sum_exp_denom = log_sum_exp(log_sum_exp_denom, 
                                          X[j] * beta + frailty[j]);
          }
        }
        log_lik[n] = numerator - log_sum_exp_denom;
      } else {
        log_lik[n] = 0;
      }
    }
}



