// Generated by paper_3_general_sampler/build_avx_models.py from Gaussian_process.stan.


// gaussian_process.stan


functions {
  real bmvp_simd_lanes();
  vector fast_exp(vector x);

    matrix example_gp_cov(array[] real left, array[] real right, real amplitude, real lengthscale) {
      int n_left = size(left);
      int n_right = size(right);
      matrix[n_left, n_right] covariance;
      for (i in 1:n_left) {
        vector[n_right] squared_distance = square(to_vector(right) - left[i]);
        covariance[i] = (square(amplitude) * fast_exp(-0.5 * squared_distance / square(lengthscale)))';
      }
      return covariance;
    }
    matrix example_gp_cov(array[] real x, real amplitude, real lengthscale) {
      return example_gp_cov(x, x, amplitude, lengthscale);
    }

    vector gp_pred_rng(array[] real x2,
                       vector y1, 
                       array[] real x1,
                       real sigma_f, 
                       real lengthscale_f,
                       real sigma,
                       real fixed_nugget_sd,
                       real jitter) {
      int N1 = rows(y1);
      int N2 = size(x2);
      vector[N2] f2;
      {
        matrix[N1, N1] L_K;
        vector[N1] K_div_y1;
        matrix[N1, N2] k_x1_x2;
        matrix[N1, N2] v_pred;
        vector[N2] f2_mu;
        matrix[N2, N2] cov_f2;
        matrix[N1, N1] K;
        
        K = example_gp_cov(x1, sigma_f, lengthscale_f);
        for (n in 1:N1) {
          K[n, n] = K[n,n] + square(sigma) + square(fixed_nugget_sd);
        }
        L_K = cholesky_decompose(K);
        K_div_y1 = mdivide_left_tri_low(L_K, y1);
        K_div_y1 = mdivide_right_tri_low(K_div_y1', L_K)';
        k_x1_x2 = example_gp_cov(x1, x2, sigma_f, lengthscale_f);
        f2_mu = (k_x1_x2' * K_div_y1);
        v_pred = mdivide_left_tri_low(L_K, k_x1_x2);
        cov_f2 = example_gp_cov(x2, sigma_f, lengthscale_f) - v_pred' * v_pred;
        f2 = multi_normal_rng(f2_mu, add_diag(cov_f2, rep_vector(jitter, N2)));
      }
      return f2;
    }
}


data {
    int<lower=2> N;          // at least two observations for standardisation
    vector[N] x;             // input locations
    vector[N] y;             // target variable
    int<lower=1> N_pred;     // number of prediction points
    vector[N_pred] x_pred;   // prediction input locations
}


transformed data {
    // Normalize data
    real x_mean = mean(x);
    real y_mean = mean(y);
    real x_sd = sd(x);
    real y_sd = sd(y);

    if (x_sd <= 0 || y_sd <= 0) {
      reject("Gaussian_process requires non-constant x and y for standardisation.");
    }
    
    array[N] real x_norm = to_array_1d((x - x_mean) / x_sd);
    array[N_pred] real x_pred_norm = to_array_1d((x_pred - x_mean) / x_sd);
    vector[N] y_norm = (y - y_mean) / y_sd;
    
    real fixed_nugget_sd = 0.05; // independent diagonal noise in standardised outcome units, not a shared intercept
    vector[N] zeros = rep_vector(0, N);
}


parameters {
    real<lower=0> lengthscale;   // lengthscale parameter
    real<lower=0> sigma_f;       // signal standard deviation
    real<lower=0> sigma_n;       // noise standard deviation
}


model {
    // Covariance matrix
    matrix[N, N] K = example_gp_cov(x_norm, sigma_f, lengthscale) + 
                     diag_matrix(rep_vector(square(fixed_nugget_sd), N));
    matrix[N, N] L_K = cholesky_decompose(add_diag(K, square(sigma_n)));
    
    // Priors
    lengthscale ~ inv_gamma(5, 5);
    sigma_f ~ std_normal();
    sigma_n ~ std_normal();
    
    // Likelihood
    y_norm ~ multi_normal_cholesky(zeros, L_K);
}


generated quantities {
    real simd_lanes = bmvp_simd_lanes();
    // Predictions scaled back to original scale
    vector[N_pred] f_pred = gp_pred_rng(x_pred_norm, y_norm, x_norm, 
                                        sigma_f, lengthscale, sigma_n, fixed_nugget_sd, 1e-9) * y_sd + y_mean;
    real sigma = sigma_n * y_sd;
}

