// Generated by paper_3_general_sampler/build_avx_models.py from hierarchical_logistic_regression.stan.
functions {
  real bmvp_simd_lanes();
  vector fast_log1p_exp(vector x);
}


// hierarchical_logistic_regression.stan

data {
    int<lower=0> N;                    // number of observations  
    int<lower=1> K;                    // number of groups
    array[N] int<lower=1, upper=K> group; // group indicator for each observation
    vector[N] x;                       // predictor variable
    array[N] int<lower=0, upper=1> y;  // binary outcome
}


parameters {
    matrix[K, 2] beta_raw;             // standard normal nuisance block, declared first
    vector[2] mu;                      // population means for [intercept, slope]
    vector<lower=0>[2] sigma;          // population standard deviations
}

transformed parameters {
    matrix[K, 2] beta;                 // group-specific intercepts and slopes
    for (i in 1:2) {
      beta[, i] = mu[i] + sigma[i] * beta_raw[, i];
    }
}

model {
    // Priors
    mu ~ normal(0, 2);
    sigma ~ normal(0, 2);
    
    // Equivalent non-centred form of beta[, i] ~ normal(mu[i], sigma[i]).
    to_vector(beta_raw) ~ std_normal();
    
    // Likelihood
    {
      vector[N] eta = beta[group, 1] + beta[group, 2] .* x;
      target += dot_product(to_vector(y), eta) - sum(fast_log1p_exp(eta));
    }
}


generated quantities {
    real simd_lanes = bmvp_simd_lanes();
    vector[N] log_lik;
    vector[N] y_rep;
    
    for (n in 1:N) {
      real eta = beta[group[n], 1] + beta[group[n], 2] * x[n];
      log_lik[n] = bernoulli_logit_lpmf(y[n] | eta);
      y_rep[n] = bernoulli_rng(inv_logit(eta));
    }
}
