// Generated by paper_3_general_sampler/build_avx_models.py from Joint_longitudinal_surv.stan.
functions {
  real bmvp_simd_lanes();
  vector fast_exp(vector x);
}


data {
  // Longitudinal data
  int<lower=1> N_long;              // number of longitudinal observations
  int<lower=1> N_subj;              // number of subjects
  int<lower=1> K_long;              // number of longitudinal covariates
  matrix[N_long, K_long] X_long;    // longitudinal covariate matrix
  vector[N_long] Y_long;            // longitudinal outcomes
  array[N_long] int<lower=1,upper=N_subj> subj_long; // subject IDs for longitudinal data
  vector[N_long] time_long;         // measurement times
  
  // Survival data
  int<lower=1> K_surv;              // number of survival covariates
  matrix[N_subj, K_surv] X_surv;    // survival covariate matrix
  vector<lower=0>[N_subj] T_surv;   // survival times
  array[N_subj] int<lower=0,upper=1> event; // event indicators
  
  // Quadrature for integration
  int<lower=1> Q;                   // number of quadrature points
  vector[Q] quad_points;            // quadrature points
  vector[Q] quad_weights;           // quadrature weights
  matrix[N_subj, K_long] X_long_event; // longitudinal fixed-effect design at T_surv
  array[N_subj] matrix[Q, K_long] X_long_quad; // same design at each subject's quadrature times
}


parameters {
  matrix[2, N_subj] b_raw;          // standard normal nuisance block, declared first
  // Longitudinal submodel parameters
  vector[K_long] beta_long;         // fixed effects
  real<lower=0> sigma_long;         // residual error SD
  real<lower=0> sigma_b0;           // random intercept SD
  real<lower=0> sigma_b1;           // random slope SD
  real<lower=-1,upper=1> rho_b;     // correlation between random effects
  
  // Survival submodel parameters
  vector[K_surv] beta_surv;         // survival covariates effects
  real<lower=0> lambda;             // baseline hazard rate
  real alpha_assoc;                 // association parameter
}


transformed parameters {
  vector[N_subj] b0 = sigma_b0 * b_raw[1]';
  vector[N_subj] b1 = sigma_b1 * (rho_b * b_raw[1]' + sqrt(1 - square(rho_b)) * b_raw[2]');
  vector[N_long] eta_long;          // longitudinal linear predictor
  vector[N_subj] hazard_subj;       // subject-specific hazards
  
  // Longitudinal linear predictor
  for (n in 1:N_long) {
    eta_long[n] = X_long[n] * beta_long + 
                  b0[subj_long[n]] + 
                  b1[subj_long[n]] * time_long[n];
  }
  
  // Subject-specific hazards at event/censoring time
  for (i in 1:N_subj) {
    real long_value = X_long_event[i] * beta_long + b0[i] + b1[i] * T_surv[i];
    hazard_subj[i] = lambda * exp(X_surv[i] * beta_surv + alpha_assoc * long_value);
  }
}


model {
  // Priors
  beta_long ~ normal(0, 2);
  beta_surv ~ normal(0, 2);
  sigma_long ~ exponential(1);
  sigma_b0 ~ exponential(1);
  sigma_b1 ~ exponential(1);
  rho_b ~ uniform(-1, 1);
  // Baseline hazard prior on the example's time scale (median 0.2 per time unit).
  lambda ~ lognormal(log(0.2), 1);
  alpha_assoc ~ normal(0, 1);
  
  // Equivalent non-centred form of the original correlated Gaussian effects.
  to_vector(b_raw) ~ std_normal();
  
  // Longitudinal likelihood
  Y_long ~ normal(eta_long, sigma_long);
  
  // Survival likelihood
  for (i in 1:N_subj) {
    // Cumulative hazard using quadrature
    real cum_hazard = 0;
    {
      vector[Q] t_q = T_surv[i] * (quad_points + 1) / 2;
      vector[Q] long_value_q = X_long_quad[i] * beta_long + b0[i] + b1[i] * t_q;
      vector[Q] log_hazard_q = log(lambda) + X_surv[i] * beta_surv + alpha_assoc * long_value_q;
      cum_hazard = dot_product(quad_weights, fast_exp(log_hazard_q)) * T_surv[i] / 2;
    }
    
    // Log-likelihood contribution
    if (event[i] == 1) {
      target += log(hazard_subj[i]) - cum_hazard;
    } else {
      target += -cum_hazard;
    }
  }
}


generated quantities {
    real simd_lanes = bmvp_simd_lanes();
  vector[N_long] y_pred;            // posterior predictions
  vector[N_subj] log_lik_surv;      // survival log-likelihood
  
  // Posterior predictions for longitudinal data
  for (n in 1:N_long) {
    y_pred[n] = normal_rng(eta_long[n], sigma_long);
  }
  
  // Log-likelihood for survival data
  for (i in 1:N_subj) {
    real cum_hazard = 0;
    {
      vector[Q] t_q = T_surv[i] * (quad_points + 1) / 2;
      vector[Q] long_value_q = X_long_quad[i] * beta_long + b0[i] + b1[i] * t_q;
      vector[Q] log_hazard_q = log(lambda) + X_surv[i] * beta_surv + alpha_assoc * long_value_q;
      cum_hazard = dot_product(quad_weights, fast_exp(log_hazard_q)) * T_surv[i] / 2;
    }
    
    if (event[i] == 1) {
      log_lik_surv[i] = log(hazard_subj[i]) - cum_hazard;
    } else {
      log_lik_surv[i] = -cum_hazard;
    }
  }
}
